/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlanVisitRouteImport } from './routes/plan-visit'
import { Route as LiveRouteImport } from './routes/live'
import { Route as InviteBishopRouteImport } from './routes/invite-bishop'
import { Route as GiveRouteImport } from './routes/give'
import { Route as FindUsRouteImport } from './routes/find-us'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BibleStudyRouteImport } from './routes/bible-study'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EventsIdRouteImport } from './routes/events_.$id'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard.programs'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard.groups'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard.finance'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardEvangelismRouteImport } from './routes/dashboard.evangelism'
import { Route as DashboardEngagementsRouteImport } from './routes/dashboard.engagements'
import { Route as DashboardBibleRouteImport } from './routes/dashboard.bible'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AboutSlugRouteImport } from './routes/about_.$slug'
import { Route as DashboardProgramsIndexRouteImport } from './routes/dashboard.programs.index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard.events.index'
import { Route as DashboardEvangelismIndexRouteImport } from './routes/dashboard.evangelism.index'
import { Route as DashboardEngagementsIndexRouteImport } from './routes/dashboard.engagements.index'
import { Route as DashboardProgramsIdRouteImport } from './routes/dashboard.programs.$id'
import { Route as DashboardGroupsIdRouteImport } from './routes/dashboard.groups.$id'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'
import { Route as DashboardEvangelismFollowUpsRouteImport } from './routes/dashboard.evangelism.follow-ups'
import { Route as DashboardEvangelismAdminRouteImport } from './routes/dashboard.evangelism.admin'
import { Route as DashboardEvangelismIdRouteImport } from './routes/dashboard.evangelism.$id'
import { Route as DashboardEngagementsSettingsRouteImport } from './routes/dashboard.engagements.settings'
import { Route as DashboardEngagementsRequestIdRouteImport } from './routes/dashboard.engagements.$requestId'
import { Route as DashboardAdminPermissionsRouteImport } from './routes/dashboard.admin.permissions'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanVisitRoute = PlanVisitRouteImport.update({
  id: '/plan-visit',
  path: '/plan-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteBishopRoute = InviteBishopRouteImport.update({
  id: '/invite-bishop',
  path: '/invite-bishop',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUsRoute = FindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleStudyRoute = BibleStudyRouteImport.update({
  id: '/bible-study',
  path: '/bible-study',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvangelismRoute = DashboardEvangelismRouteImport.update({
  id: '/evangelism',
  path: '/evangelism',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEngagementsRoute = DashboardEngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBibleRoute = DashboardBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const AboutSlugRoute = AboutSlugRouteImport.update({
  id: '/about_/$slug',
  path: '/about/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramsIndexRoute = DashboardProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProgramsRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardEvangelismIndexRoute =
  DashboardEvangelismIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEvangelismRoute,
  } as any)
const DashboardEngagementsIndexRoute =
  DashboardEngagementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEngagementsRoute,
  } as any)
const DashboardProgramsIdRoute = DashboardProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProgramsRoute,
} as any)
const DashboardGroupsIdRoute = DashboardGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardGroupsRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardEvangelismFollowUpsRoute =
  DashboardEvangelismFollowUpsRouteImport.update({
    id: '/follow-ups',
    path: '/follow-ups',
    getParentRoute: () => DashboardEvangelismRoute,
  } as any)
const DashboardEvangelismAdminRoute =
  DashboardEvangelismAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => DashboardEvangelismRoute,
  } as any)
const DashboardEvangelismIdRoute = DashboardEvangelismIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEvangelismRoute,
} as any)
const DashboardEngagementsSettingsRoute =
  DashboardEngagementsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardEngagementsRoute,
  } as any)
const DashboardEngagementsRequestIdRoute =
  DashboardEngagementsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => DashboardEngagementsRoute,
  } as any)
const DashboardAdminPermissionsRoute =
  DashboardAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bible-study': typeof BibleStudyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/find-us': typeof FindUsRoute
  '/give': typeof GiveRoute
  '/invite-bishop': typeof InviteBishopRoute
  '/live': typeof LiveRoute
  '/plan-visit': typeof PlanVisitRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/bible': typeof DashboardBibleRoute
  '/dashboard/engagements': typeof DashboardEngagementsRouteWithChildren
  '/dashboard/evangelism': typeof DashboardEvangelismRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/services': typeof DashboardServicesRoute
  '/events/$id': typeof EventsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/engagements/$requestId': typeof DashboardEngagementsRequestIdRoute
  '/dashboard/engagements/settings': typeof DashboardEngagementsSettingsRoute
  '/dashboard/evangelism/$id': typeof DashboardEvangelismIdRoute
  '/dashboard/evangelism/admin': typeof DashboardEvangelismAdminRoute
  '/dashboard/evangelism/follow-ups': typeof DashboardEvangelismFollowUpsRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/dashboard/programs/$id': typeof DashboardProgramsIdRoute
  '/dashboard/engagements/': typeof DashboardEngagementsIndexRoute
  '/dashboard/evangelism/': typeof DashboardEvangelismIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/programs/': typeof DashboardProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bible-study': typeof BibleStudyRoute
  '/events': typeof EventsRoute
  '/find-us': typeof FindUsRoute
  '/give': typeof GiveRoute
  '/invite-bishop': typeof InviteBishopRoute
  '/live': typeof LiveRoute
  '/plan-visit': typeof PlanVisitRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/about/$slug': typeof AboutSlugRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/bible': typeof DashboardBibleRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/services': typeof DashboardServicesRoute
  '/events/$id': typeof EventsIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/engagements/$requestId': typeof DashboardEngagementsRequestIdRoute
  '/dashboard/engagements/settings': typeof DashboardEngagementsSettingsRoute
  '/dashboard/evangelism/$id': typeof DashboardEvangelismIdRoute
  '/dashboard/evangelism/admin': typeof DashboardEvangelismAdminRoute
  '/dashboard/evangelism/follow-ups': typeof DashboardEvangelismFollowUpsRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/dashboard/programs/$id': typeof DashboardProgramsIdRoute
  '/dashboard/engagements': typeof DashboardEngagementsIndexRoute
  '/dashboard/evangelism': typeof DashboardEvangelismIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/programs': typeof DashboardProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bible-study': typeof BibleStudyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/find-us': typeof FindUsRoute
  '/give': typeof GiveRoute
  '/invite-bishop': typeof InviteBishopRoute
  '/live': typeof LiveRoute
  '/plan-visit': typeof PlanVisitRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/about_/$slug': typeof AboutSlugRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/bible': typeof DashboardBibleRoute
  '/dashboard/engagements': typeof DashboardEngagementsRouteWithChildren
  '/dashboard/evangelism': typeof DashboardEvangelismRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/dashboard/services': typeof DashboardServicesRoute
  '/events_/$id': typeof EventsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/engagements/$requestId': typeof DashboardEngagementsRequestIdRoute
  '/dashboard/engagements/settings': typeof DashboardEngagementsSettingsRoute
  '/dashboard/evangelism/$id': typeof DashboardEvangelismIdRoute
  '/dashboard/evangelism/admin': typeof DashboardEvangelismAdminRoute
  '/dashboard/evangelism/follow-ups': typeof DashboardEvangelismFollowUpsRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/dashboard/programs/$id': typeof DashboardProgramsIdRoute
  '/dashboard/engagements/': typeof DashboardEngagementsIndexRoute
  '/dashboard/evangelism/': typeof DashboardEvangelismIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/programs/': typeof DashboardProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bible-study'
    | '/dashboard'
    | '/events'
    | '/find-us'
    | '/give'
    | '/invite-bishop'
    | '/live'
    | '/plan-visit'
    | '/privacy-policy'
    | '/terms'
    | '/about/$slug'
    | '/dashboard/admin'
    | '/dashboard/bible'
    | '/dashboard/engagements'
    | '/dashboard/evangelism'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/groups'
    | '/dashboard/programs'
    | '/dashboard/services'
    | '/events/$id'
    | '/dashboard/'
    | '/dashboard/admin/permissions'
    | '/dashboard/engagements/$requestId'
    | '/dashboard/engagements/settings'
    | '/dashboard/evangelism/$id'
    | '/dashboard/evangelism/admin'
    | '/dashboard/evangelism/follow-ups'
    | '/dashboard/events/$id'
    | '/dashboard/groups/$id'
    | '/dashboard/programs/$id'
    | '/dashboard/engagements/'
    | '/dashboard/evangelism/'
    | '/dashboard/events/'
    | '/dashboard/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bible-study'
    | '/events'
    | '/find-us'
    | '/give'
    | '/invite-bishop'
    | '/live'
    | '/plan-visit'
    | '/privacy-policy'
    | '/terms'
    | '/about/$slug'
    | '/dashboard/admin'
    | '/dashboard/bible'
    | '/dashboard/finance'
    | '/dashboard/groups'
    | '/dashboard/services'
    | '/events/$id'
    | '/dashboard'
    | '/dashboard/admin/permissions'
    | '/dashboard/engagements/$requestId'
    | '/dashboard/engagements/settings'
    | '/dashboard/evangelism/$id'
    | '/dashboard/evangelism/admin'
    | '/dashboard/evangelism/follow-ups'
    | '/dashboard/events/$id'
    | '/dashboard/groups/$id'
    | '/dashboard/programs/$id'
    | '/dashboard/engagements'
    | '/dashboard/evangelism'
    | '/dashboard/events'
    | '/dashboard/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bible-study'
    | '/dashboard'
    | '/events'
    | '/find-us'
    | '/give'
    | '/invite-bishop'
    | '/live'
    | '/plan-visit'
    | '/privacy-policy'
    | '/terms'
    | '/about_/$slug'
    | '/dashboard/admin'
    | '/dashboard/bible'
    | '/dashboard/engagements'
    | '/dashboard/evangelism'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/groups'
    | '/dashboard/programs'
    | '/dashboard/services'
    | '/events_/$id'
    | '/dashboard/'
    | '/dashboard/admin/permissions'
    | '/dashboard/engagements/$requestId'
    | '/dashboard/engagements/settings'
    | '/dashboard/evangelism/$id'
    | '/dashboard/evangelism/admin'
    | '/dashboard/evangelism/follow-ups'
    | '/dashboard/events/$id'
    | '/dashboard/groups/$id'
    | '/dashboard/programs/$id'
    | '/dashboard/engagements/'
    | '/dashboard/evangelism/'
    | '/dashboard/events/'
    | '/dashboard/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BibleStudyRoute: typeof BibleStudyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  FindUsRoute: typeof FindUsRoute
  GiveRoute: typeof GiveRoute
  InviteBishopRoute: typeof InviteBishopRoute
  LiveRoute: typeof LiveRoute
  PlanVisitRoute: typeof PlanVisitRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  AboutSlugRoute: typeof AboutSlugRoute
  EventsIdRoute: typeof EventsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-visit': {
      id: '/plan-visit'
      path: '/plan-visit'
      fullPath: '/plan-visit'
      preLoaderRoute: typeof PlanVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-bishop': {
      id: '/invite-bishop'
      path: '/invite-bishop'
      fullPath: '/invite-bishop'
      preLoaderRoute: typeof InviteBishopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-us': {
      id: '/find-us'
      path: '/find-us'
      fullPath: '/find-us'
      preLoaderRoute: typeof FindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-study': {
      id: '/bible-study'
      path: '/bible-study'
      fullPath: '/bible-study'
      preLoaderRoute: typeof BibleStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events_/$id': {
      id: '/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs': {
      id: '/dashboard/programs'
      path: '/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evangelism': {
      id: '/dashboard/evangelism'
      path: '/evangelism'
      fullPath: '/dashboard/evangelism'
      preLoaderRoute: typeof DashboardEvangelismRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/engagements': {
      id: '/dashboard/engagements'
      path: '/engagements'
      fullPath: '/dashboard/engagements'
      preLoaderRoute: typeof DashboardEngagementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bible': {
      id: '/dashboard/bible'
      path: '/bible'
      fullPath: '/dashboard/bible'
      preLoaderRoute: typeof DashboardBibleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/about_/$slug': {
      id: '/about_/$slug'
      path: '/about/$slug'
      fullPath: '/about/$slug'
      preLoaderRoute: typeof AboutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/programs/': {
      id: '/dashboard/programs/'
      path: '/'
      fullPath: '/dashboard/programs/'
      preLoaderRoute: typeof DashboardProgramsIndexRouteImport
      parentRoute: typeof DashboardProgramsRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/evangelism/': {
      id: '/dashboard/evangelism/'
      path: '/'
      fullPath: '/dashboard/evangelism/'
      preLoaderRoute: typeof DashboardEvangelismIndexRouteImport
      parentRoute: typeof DashboardEvangelismRoute
    }
    '/dashboard/engagements/': {
      id: '/dashboard/engagements/'
      path: '/'
      fullPath: '/dashboard/engagements/'
      preLoaderRoute: typeof DashboardEngagementsIndexRouteImport
      parentRoute: typeof DashboardEngagementsRoute
    }
    '/dashboard/programs/$id': {
      id: '/dashboard/programs/$id'
      path: '/$id'
      fullPath: '/dashboard/programs/$id'
      preLoaderRoute: typeof DashboardProgramsIdRouteImport
      parentRoute: typeof DashboardProgramsRoute
    }
    '/dashboard/groups/$id': {
      id: '/dashboard/groups/$id'
      path: '/$id'
      fullPath: '/dashboard/groups/$id'
      preLoaderRoute: typeof DashboardGroupsIdRouteImport
      parentRoute: typeof DashboardGroupsRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/evangelism/follow-ups': {
      id: '/dashboard/evangelism/follow-ups'
      path: '/follow-ups'
      fullPath: '/dashboard/evangelism/follow-ups'
      preLoaderRoute: typeof DashboardEvangelismFollowUpsRouteImport
      parentRoute: typeof DashboardEvangelismRoute
    }
    '/dashboard/evangelism/admin': {
      id: '/dashboard/evangelism/admin'
      path: '/admin'
      fullPath: '/dashboard/evangelism/admin'
      preLoaderRoute: typeof DashboardEvangelismAdminRouteImport
      parentRoute: typeof DashboardEvangelismRoute
    }
    '/dashboard/evangelism/$id': {
      id: '/dashboard/evangelism/$id'
      path: '/$id'
      fullPath: '/dashboard/evangelism/$id'
      preLoaderRoute: typeof DashboardEvangelismIdRouteImport
      parentRoute: typeof DashboardEvangelismRoute
    }
    '/dashboard/engagements/settings': {
      id: '/dashboard/engagements/settings'
      path: '/settings'
      fullPath: '/dashboard/engagements/settings'
      preLoaderRoute: typeof DashboardEngagementsSettingsRouteImport
      parentRoute: typeof DashboardEngagementsRoute
    }
    '/dashboard/engagements/$requestId': {
      id: '/dashboard/engagements/$requestId'
      path: '/$requestId'
      fullPath: '/dashboard/engagements/$requestId'
      preLoaderRoute: typeof DashboardEngagementsRequestIdRouteImport
      parentRoute: typeof DashboardEngagementsRoute
    }
    '/dashboard/admin/permissions': {
      id: '/dashboard/admin/permissions'
      path: '/permissions'
      fullPath: '/dashboard/admin/permissions'
      preLoaderRoute: typeof DashboardAdminPermissionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminPermissionsRoute: typeof DashboardAdminPermissionsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminPermissionsRoute: DashboardAdminPermissionsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardEngagementsRouteChildren {
  DashboardEngagementsRequestIdRoute: typeof DashboardEngagementsRequestIdRoute
  DashboardEngagementsSettingsRoute: typeof DashboardEngagementsSettingsRoute
  DashboardEngagementsIndexRoute: typeof DashboardEngagementsIndexRoute
}

const DashboardEngagementsRouteChildren: DashboardEngagementsRouteChildren = {
  DashboardEngagementsRequestIdRoute: DashboardEngagementsRequestIdRoute,
  DashboardEngagementsSettingsRoute: DashboardEngagementsSettingsRoute,
  DashboardEngagementsIndexRoute: DashboardEngagementsIndexRoute,
}

const DashboardEngagementsRouteWithChildren =
  DashboardEngagementsRoute._addFileChildren(DashboardEngagementsRouteChildren)

interface DashboardEvangelismRouteChildren {
  DashboardEvangelismIdRoute: typeof DashboardEvangelismIdRoute
  DashboardEvangelismAdminRoute: typeof DashboardEvangelismAdminRoute
  DashboardEvangelismFollowUpsRoute: typeof DashboardEvangelismFollowUpsRoute
  DashboardEvangelismIndexRoute: typeof DashboardEvangelismIndexRoute
}

const DashboardEvangelismRouteChildren: DashboardEvangelismRouteChildren = {
  DashboardEvangelismIdRoute: DashboardEvangelismIdRoute,
  DashboardEvangelismAdminRoute: DashboardEvangelismAdminRoute,
  DashboardEvangelismFollowUpsRoute: DashboardEvangelismFollowUpsRoute,
  DashboardEvangelismIndexRoute: DashboardEvangelismIndexRoute,
}

const DashboardEvangelismRouteWithChildren =
  DashboardEvangelismRoute._addFileChildren(DashboardEvangelismRouteChildren)

interface DashboardEventsRouteChildren {
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
)

interface DashboardGroupsRouteChildren {
  DashboardGroupsIdRoute: typeof DashboardGroupsIdRoute
}

const DashboardGroupsRouteChildren: DashboardGroupsRouteChildren = {
  DashboardGroupsIdRoute: DashboardGroupsIdRoute,
}

const DashboardGroupsRouteWithChildren = DashboardGroupsRoute._addFileChildren(
  DashboardGroupsRouteChildren,
)

interface DashboardProgramsRouteChildren {
  DashboardProgramsIdRoute: typeof DashboardProgramsIdRoute
  DashboardProgramsIndexRoute: typeof DashboardProgramsIndexRoute
}

const DashboardProgramsRouteChildren: DashboardProgramsRouteChildren = {
  DashboardProgramsIdRoute: DashboardProgramsIdRoute,
  DashboardProgramsIndexRoute: DashboardProgramsIndexRoute,
}

const DashboardProgramsRouteWithChildren =
  DashboardProgramsRoute._addFileChildren(DashboardProgramsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardBibleRoute: typeof DashboardBibleRoute
  DashboardEngagementsRoute: typeof DashboardEngagementsRouteWithChildren
  DashboardEvangelismRoute: typeof DashboardEvangelismRouteWithChildren
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardGroupsRoute: typeof DashboardGroupsRouteWithChildren
  DashboardProgramsRoute: typeof DashboardProgramsRouteWithChildren
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardBibleRoute: DashboardBibleRoute,
  DashboardEngagementsRoute: DashboardEngagementsRouteWithChildren,
  DashboardEvangelismRoute: DashboardEvangelismRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardGroupsRoute: DashboardGroupsRouteWithChildren,
  DashboardProgramsRoute: DashboardProgramsRouteWithChildren,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BibleStudyRoute: BibleStudyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  FindUsRoute: FindUsRoute,
  GiveRoute: GiveRoute,
  InviteBishopRoute: InviteBishopRoute,
  LiveRoute: LiveRoute,
  PlanVisitRoute: PlanVisitRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  AboutSlugRoute: AboutSlugRoute,
  EventsIdRoute: EventsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
