/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanVisitRouteImport } from './routes/plan-visit'
import { Route as GiveRouteImport } from './routes/give'
import { Route as FindUsRouteImport } from './routes/find-us'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard.programs'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard.groups'
import { Route as DashboardFollowUpsRouteImport } from './routes/dashboard.follow-ups'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardEvangelismRouteImport } from './routes/dashboard.evangelism'
import { Route as DashboardBibleRouteImport } from './routes/dashboard.bible'
import { Route as DashboardProgramsIndexRouteImport } from './routes/dashboard.programs.index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard.events.index'
import { Route as DashboardEvangelismIndexRouteImport } from './routes/dashboard.evangelism.index'
import { Route as DashboardProgramsIdRouteImport } from './routes/dashboard.programs.$id'
import { Route as DashboardGroupsIdRouteImport } from './routes/dashboard.groups.$id'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'
import { Route as DashboardEvangelismIdRouteImport } from './routes/dashboard.evangelism.$id'

const PlanVisitRoute = PlanVisitRouteImport.update({
  id: '/plan-visit',
  path: '/plan-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUsRoute = FindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFollowUpsRoute = DashboardFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvangelismRoute = DashboardEvangelismRouteImport.update({
  id: '/evangelism',
  path: '/evangelism',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBibleRoute = DashboardBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgramsIndexRoute = DashboardProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProgramsRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardEvangelismIndexRoute =
  DashboardEvangelismIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEvangelismRoute,
  } as any)
const DashboardProgramsIdRoute = DashboardProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardProgramsRoute,
} as any)
const DashboardGroupsIdRoute = DashboardGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardGroupsRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEventsRoute,
} as any)
const DashboardEvangelismIdRoute = DashboardEvangelismIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEvangelismRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/find-us': typeof FindUsRoute
  '/give': typeof GiveRoute
  '/plan-visit': typeof PlanVisitRoute
  '/dashboard/bible': typeof DashboardBibleRoute
  '/dashboard/evangelism': typeof DashboardEvangelismRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/follow-ups': typeof DashboardFollowUpsRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/evangelism/$id': typeof DashboardEvangelismIdRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/dashboard/programs/$id': typeof DashboardProgramsIdRoute
  '/dashboard/evangelism/': typeof DashboardEvangelismIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/programs/': typeof DashboardProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/find-us': typeof FindUsRoute
  '/give': typeof GiveRoute
  '/plan-visit': typeof PlanVisitRoute
  '/dashboard/bible': typeof DashboardBibleRoute
  '/dashboard/follow-ups': typeof DashboardFollowUpsRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/evangelism/$id': typeof DashboardEvangelismIdRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/dashboard/programs/$id': typeof DashboardProgramsIdRoute
  '/dashboard/evangelism': typeof DashboardEvangelismIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/programs': typeof DashboardProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/find-us': typeof FindUsRoute
  '/give': typeof GiveRoute
  '/plan-visit': typeof PlanVisitRoute
  '/dashboard/bible': typeof DashboardBibleRoute
  '/dashboard/evangelism': typeof DashboardEvangelismRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/follow-ups': typeof DashboardFollowUpsRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/programs': typeof DashboardProgramsRouteWithChildren
  '/events/$id': typeof EventsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/evangelism/$id': typeof DashboardEvangelismIdRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/dashboard/programs/$id': typeof DashboardProgramsIdRoute
  '/dashboard/evangelism/': typeof DashboardEvangelismIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/programs/': typeof DashboardProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/events'
    | '/find-us'
    | '/give'
    | '/plan-visit'
    | '/dashboard/bible'
    | '/dashboard/evangelism'
    | '/dashboard/events'
    | '/dashboard/follow-ups'
    | '/dashboard/groups'
    | '/dashboard/programs'
    | '/events/$id'
    | '/dashboard/'
    | '/dashboard/evangelism/$id'
    | '/dashboard/events/$id'
    | '/dashboard/groups/$id'
    | '/dashboard/programs/$id'
    | '/dashboard/evangelism/'
    | '/dashboard/events/'
    | '/dashboard/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/events'
    | '/find-us'
    | '/give'
    | '/plan-visit'
    | '/dashboard/bible'
    | '/dashboard/follow-ups'
    | '/dashboard/groups'
    | '/events/$id'
    | '/dashboard'
    | '/dashboard/evangelism/$id'
    | '/dashboard/events/$id'
    | '/dashboard/groups/$id'
    | '/dashboard/programs/$id'
    | '/dashboard/evangelism'
    | '/dashboard/events'
    | '/dashboard/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/events'
    | '/find-us'
    | '/give'
    | '/plan-visit'
    | '/dashboard/bible'
    | '/dashboard/evangelism'
    | '/dashboard/events'
    | '/dashboard/follow-ups'
    | '/dashboard/groups'
    | '/dashboard/programs'
    | '/events/$id'
    | '/dashboard/'
    | '/dashboard/evangelism/$id'
    | '/dashboard/events/$id'
    | '/dashboard/groups/$id'
    | '/dashboard/programs/$id'
    | '/dashboard/evangelism/'
    | '/dashboard/events/'
    | '/dashboard/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  FindUsRoute: typeof FindUsRoute
  GiveRoute: typeof GiveRoute
  PlanVisitRoute: typeof PlanVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plan-visit': {
      id: '/plan-visit'
      path: '/plan-visit'
      fullPath: '/plan-visit'
      preLoaderRoute: typeof PlanVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-us': {
      id: '/find-us'
      path: '/find-us'
      fullPath: '/find-us'
      preLoaderRoute: typeof FindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/programs': {
      id: '/dashboard/programs'
      path: '/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/follow-ups': {
      id: '/dashboard/follow-ups'
      path: '/follow-ups'
      fullPath: '/dashboard/follow-ups'
      preLoaderRoute: typeof DashboardFollowUpsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evangelism': {
      id: '/dashboard/evangelism'
      path: '/evangelism'
      fullPath: '/dashboard/evangelism'
      preLoaderRoute: typeof DashboardEvangelismRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bible': {
      id: '/dashboard/bible'
      path: '/bible'
      fullPath: '/dashboard/bible'
      preLoaderRoute: typeof DashboardBibleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programs/': {
      id: '/dashboard/programs/'
      path: '/'
      fullPath: '/dashboard/programs/'
      preLoaderRoute: typeof DashboardProgramsIndexRouteImport
      parentRoute: typeof DashboardProgramsRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/evangelism/': {
      id: '/dashboard/evangelism/'
      path: '/'
      fullPath: '/dashboard/evangelism/'
      preLoaderRoute: typeof DashboardEvangelismIndexRouteImport
      parentRoute: typeof DashboardEvangelismRoute
    }
    '/dashboard/programs/$id': {
      id: '/dashboard/programs/$id'
      path: '/$id'
      fullPath: '/dashboard/programs/$id'
      preLoaderRoute: typeof DashboardProgramsIdRouteImport
      parentRoute: typeof DashboardProgramsRoute
    }
    '/dashboard/groups/$id': {
      id: '/dashboard/groups/$id'
      path: '/$id'
      fullPath: '/dashboard/groups/$id'
      preLoaderRoute: typeof DashboardGroupsIdRouteImport
      parentRoute: typeof DashboardGroupsRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
    '/dashboard/evangelism/$id': {
      id: '/dashboard/evangelism/$id'
      path: '/$id'
      fullPath: '/dashboard/evangelism/$id'
      preLoaderRoute: typeof DashboardEvangelismIdRouteImport
      parentRoute: typeof DashboardEvangelismRoute
    }
  }
}

interface DashboardEvangelismRouteChildren {
  DashboardEvangelismIdRoute: typeof DashboardEvangelismIdRoute
  DashboardEvangelismIndexRoute: typeof DashboardEvangelismIndexRoute
}

const DashboardEvangelismRouteChildren: DashboardEvangelismRouteChildren = {
  DashboardEvangelismIdRoute: DashboardEvangelismIdRoute,
  DashboardEvangelismIndexRoute: DashboardEvangelismIndexRoute,
}

const DashboardEvangelismRouteWithChildren =
  DashboardEvangelismRoute._addFileChildren(DashboardEvangelismRouteChildren)

interface DashboardEventsRouteChildren {
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
)

interface DashboardGroupsRouteChildren {
  DashboardGroupsIdRoute: typeof DashboardGroupsIdRoute
}

const DashboardGroupsRouteChildren: DashboardGroupsRouteChildren = {
  DashboardGroupsIdRoute: DashboardGroupsIdRoute,
}

const DashboardGroupsRouteWithChildren = DashboardGroupsRoute._addFileChildren(
  DashboardGroupsRouteChildren,
)

interface DashboardProgramsRouteChildren {
  DashboardProgramsIdRoute: typeof DashboardProgramsIdRoute
  DashboardProgramsIndexRoute: typeof DashboardProgramsIndexRoute
}

const DashboardProgramsRouteChildren: DashboardProgramsRouteChildren = {
  DashboardProgramsIdRoute: DashboardProgramsIdRoute,
  DashboardProgramsIndexRoute: DashboardProgramsIndexRoute,
}

const DashboardProgramsRouteWithChildren =
  DashboardProgramsRoute._addFileChildren(DashboardProgramsRouteChildren)

interface DashboardRouteChildren {
  DashboardBibleRoute: typeof DashboardBibleRoute
  DashboardEvangelismRoute: typeof DashboardEvangelismRouteWithChildren
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren
  DashboardFollowUpsRoute: typeof DashboardFollowUpsRoute
  DashboardGroupsRoute: typeof DashboardGroupsRouteWithChildren
  DashboardProgramsRoute: typeof DashboardProgramsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBibleRoute: DashboardBibleRoute,
  DashboardEvangelismRoute: DashboardEvangelismRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardFollowUpsRoute: DashboardFollowUpsRoute,
  DashboardGroupsRoute: DashboardGroupsRouteWithChildren,
  DashboardProgramsRoute: DashboardProgramsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  FindUsRoute: FindUsRoute,
  GiveRoute: GiveRoute,
  PlanVisitRoute: PlanVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
